### ISSUE TITLE
Umbrella 1.0

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#143]
As Look slowly matures, we soon might consider going 1.0. Therefore these things need to be fixed/implemented.
 
- [x] Codemod to upgrade smoothly from 0.7 to 1.0
- [x] pure stateless function support ( #215 )
- [x] single prefixer instance ( #237 )
- [ ] black-box tests ( #234 )
- [x] Test utils package
