### ISSUE TITLE
Umbrella server-side rendering

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#144]
In order to have full server-side rendering support certain things need to be fixed.

There are some main goals to achieve:
- [x] Media queries need to be converted to static CSS on the initial load
- [x] GlobalStyleSheet (CSSContainer instance) to collect CSS rendered strings
- [x] Inject a style sheet after the root element (prevents false rendering order)
- [x] allow global Look config on root component

#### Linked issues
- [x] GlobalStyleSheet throws because document is undefined ( #139 ) 
- [x] mediaQuery to CSS - initial load ( #4 )
- [x] config as prop ( #150 )

**Comment by rofrischmann** [comment]
Suprise! Server-side rendering now is fully supported whooraay!
