### ISSUE TITLE
Umbrella DX

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#151]
As Look slowly matures and gets near to a 1.0 release we might think about adding some DX plugins.

Simple examples would be:
- [x] onClick, onRender, onHover StyleLogger ( #153 )

### Linting tools
- [ ] Browser issue warnings
- [x] Prefix warnings (if manually added prefixes) ( #154 )
- [x] shorthand warnings (if shorthand and longhand  props are mixed)

Also important would be:
- [x] Flatten packages ( #152 )

**Comment by rofrischmann** [comment]
Now that inline-style-linter can be used, all DX feature requests belong to that repository. Therefore we can close this.
